receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed
  otlphttp/openobserve:
    endpoint: "https://openobserve.thenerdcompany.us/api/default/"
    headers:
      Authorization: "Basic Z3VpbGxhdW1lLmJhaWxsZXVsQGdtYWlsLmNvbTpXNkIycGdXNjVlUXRxVDVBdFNZRQ=="
      stream-name: wecraft_dev

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/openobserve, debug]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/openobserve]
    traces:
      receivers: [otlp]
      exporters: [otlphttp/openobserve]
